# -*- coding: utf-8 -*-
"""project_sepeher_erfan

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w8k7BO9QfRbTUs4gvVM9we7r-1k8jUDS
"""

from diffusers import StableDiffusionPipeline
import torch

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
pipeline = StableDiffusionPipeline.from_pretrained('simonschoe/pokeball-machine').to(device)

prompt = "a pkblz ball in the middle of a miniature jungle"

image = pipeline(
    prompt,
    num_inference_steps=50,
    guidance_scale=10,
    num_images_per_prompt=1
).images[0]

!pip install torch